package dev.progrover.vktestcase.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class AppColors(
    val main: Color,
    val bordersColor: Color,
    val background: Color,
    val hint: Color,
    val accentVariant: Color,
    val title: Color,
    val marksText: Color,
    val text: Color,
    val surface: Color,
    val textFieldBackground: Color,
    val unselectedBNI: Color,
    val error: Color,
    val warning: Color,
    val container: Color,
    val white: Color,
    val black: Color,
    val primary: Color,
    val light: Color,
    val gray_100: Color,
    val gray_200: Color,
    val gray_300: Color,
    val gray_400: Color,
    val gray_500: Color,
    val gray_600: Color,
    val gray_700: Color,
    val gray_800: Color,
    val gray_900: Color,
    val yellow: Color,
    val red: Color,
    val green: Color,
) {
    companion object {
        val LightColors = AppColors(
            main = Color(0xFF7C6A46),
            bordersColor = Color(0xFFEBEBEB),
            background = Color(0xFFFFFFFF),
            hint = Color(0xFF9F9F9F),
            accentVariant = Color(0xFF434242),
            title = Color(0xFFFEFEFE),
            marksText = Color(0xFFACAFB4),
            text = Color(0xFF151515),
            surface = Color(0xFFFEFEFE),
            textFieldBackground = Color(0xFFF6F6F6),
            error = Color(0xFFE30A25),
            warning = Color(0xFFEF7B23),
            container = Color(0xFFF7F7F7),
            unselectedBNI = Color(0xFFC2C2C2),
            black = Color(0xFF202022),
            white = Color(0xFFFFFFFF),
            primary = Color(0xFF7C6A46),
            light = Color(0xFFF1EDE7),
            gray_100 = Color(0xFFFAFAFA),
            gray_200 = Color(0xFFF6F6F6),
            gray_300 = Color(0xFFEAEBEC),
            gray_400 = Color(0xFFDCDEE0),
            gray_500 = Color(0xFFC7CACD),
            gray_600 = Color(0xFFB2B5B9),
            gray_700 = Color(0xFF90959B),
            gray_800 = Color(0xFF747A82),
            gray_900 = Color(0xFF454B53),
            yellow = Color(0xFFF1B51A),
            red = Color(0xFFF6152B),
            green = Color(0xFF2CAE2C),
        )

        val DarkColors = AppColors(
            main = Color(0xFF7C6A46),
            bordersColor = Color(0xFFEBEBEB),
            background = Color(0xFFFFFFFF),
            hint = Color(0xFF9F9F9F),
            accentVariant = Color(0xFF434242),
            title = Color(0xFFFEFEFE),
            marksText = Color(0xFFACAFB4),
            text = Color(0xFF151515),
            surface = Color(0xFFFEFEFE),
            textFieldBackground = Color(0xFFF6F6F6),
            error = Color(0xFFE30A25),
            warning = Color(0xFFEF7B23),
            container = Color(0xFFF7F7F7),
            unselectedBNI = Color(0xFFC2C2C2),
            black = Color(0xFF202022),
            white = Color(0xFFFFFFFF),
            primary = Color(0xFF7C6A46),
            light = Color(0xFFF1EDE7),
            gray_100 = Color(0xFFFAFAFA),
            gray_200 = Color(0xFFF6F6F6),
            gray_300 = Color(0xFFEAEBEC),
            gray_400 = Color(0xFFDCDEE0),
            gray_500 = Color(0xFFC7CACD),
            gray_600 = Color(0xFFB2B5B9),
            gray_700 = Color(0xFF90959B),
            gray_800 = Color(0xFF747A82),
            gray_900 = Color(0xFF454B53),
            yellow = Color(0xFFF1B51A),
            red = Color(0xFFF6152B),
            green = Color(0xFF2CAE2C),
        )
    }
}

internal val LocalAppColors = staticCompositionLocalOf {
    AppColors.LightColors
}